version: '2'
services:
  web_netty_server:
    build: 
          args:
               home_dir: /home/mail
          context: .
    ports:
          - "8080:80"
    volumes:
          - ./static/http-test-suite:/home/mail/static
